### PR TITLE
- The line "use Test::NoWarnings;" not required in the 03-map.t script.

### PR DESCRIPTION
**Pull request by manwar**
Hi ,

Please review the suggested change.

Many Thanks.

Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
Hi,

I am placing Test::NoWarning to all tests due possibility of warning.
As i understand, you say, that warning isn't possible in this place?

In reality:
Whey you create second $TEST->plan() in Test::Map::Tube, Test::Builder->plan creates warnings.
And this is for these checks in modules above my module.

I am for use of this test.

M.

**Comment by manwar** [comment]
HI,

Do you have a script that can generate such warnings?
I am curious to know. 
It would help me to fix it in the Test::Map::Tube package so that you don't have to deal with it.

Best Regards,
Mohammad S Anwar

**Comment by michal-josef-spacek** [comment]
> Do you have a script that can generate such warnings?

No.
That isn't point.
But, when anybody creates warning (Test::Map::Tube, Test::Builder, etc.), in my test it trigger fail.

M.

**Comment by michal-josef-spacek** [comment]
For example: http://www.cpantesters.org/cpan/report/968a3680-6e00-11e5-aa10-096acfe82091

**Comment by manwar** [comment]
Hi,

Thanks for the link. It really helps in debugging the core issue.

It appears XML::Simple (xml processing library used by Map::Tube) is not behaving with XML::SAX v0.99 is installed. It worked in my local environment where I have XML::SAX v0.96.However when I upgraded it to v0.99, I start getting the same warnings.

I have been thinking of replacing XML::Simple with some sensible parser, I spoke to few experts in XML processing and they recommended XML::Twig. I have now updated Map::Tube to use XML::Twig instead and this fixed the warnings;

I will try to push the updated Map::Tube v3.02 sometimes tomorrow. With the new version, your 03-map.t should look like:

  # Pragmas.
  use strict;
  use warnings;

  # Modules.
  use Map::Tube::Moscow;
  use Test::Map::Tube;

  # Test.
  ok_map(Map::Tube::Moscow->new, 'Test validity of map.');

This also means, you can now merge my proposed changes, once you have Map::Tube v3.02.

Best Regards,
Mohammad S Anwar

**Comment by michal-josef-spacek** [comment]
Hi,
It was great, if you found and resolve this problem. Thanks.

But that's no point of my Test::NoWarnings.
When anybody in future create another problem like this, this test trigger it.
That's no your problem, no in your module.
This is important for me as developer, that is something bad in dependency of every modules, which i am using.
:-)

Kind regards,
M.

**Pull request closed without merging**
